n = int(input("Nhap so nguyen n = "))
hexa = hex(n)
octa = oct(n)
bina = bin(n)
print("He co so 16 co dang: " + str(hexa))
print("He co so 8 co dang : " + str(octa))
print("He co so 2 co dang : " + str(bina))
